FROM golang:1.16.3-buster AS builder

WORKDIR /go/src/github.com/valerauko/panther

COPY go.mod .
COPY go.sum .
COPY server.go .

RUN go build

FROM debian:buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /go/src/github.com/valerauko/panther/panther .

CMD ["./panther"]
