version: '3'
services:
  panther:
    build: .
    environment:
      CIVO_API_REGION: ${CIVO_API_REGION}
      CIVO_API_TOKEN: ${CIVO_API_TOKEN}
    volumes:
      - ./:/go/src/github.com/valerauko/panther
    ports:
      - 8080:8080
    command: go run server.go
