name: Build and push Panther Docker image

on:
  push:
    branches: [ main ]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        id: build-image
        run: |
          set -euo pipefail
          image=valerauko/panther:$(git rev-parse --short HEAD)
          docker build -f Dockerfile.prod -t "$image" .
          echo "::set-output name=image::$image"
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login ghcr.io -u valerauko --password-stdin
      - name: Push Docker image
        run: docker push "ghcr.io/${{ steps.build-image.outputs.image }}"
