name: Build and push Panther Docker image

on:
  push:
    branches: [ main ]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          set -euo pipefail
          image=valerauko/panther:$(git rev-parse --short HEAD)
          docker build -f Dockerfile.prod -t "$image" .
          echo "::set-output name=image::$image"
      - name: Push Docker image
        run: docker push "ghcr.io/$image"
