name: Release Panther Docker image

on:
  push:
    branches: [ main ]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        id: build-image
        run: |
          set -euo pipefail
          image=valerauko/panther:$(git rev-parse --short HEAD)
          docker build -f Dockerfile.prod -t "$image" .
          echo "::set-output name=image::$image"
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | \
          docker login ghcr.io -u valerauko --password-stdin
      - name: Push Docker image
        run: |
          set -euo pipefail
          image=${{ steps.build-image.outputs.image }}
          docker tag "$image" "ghcr.io/$image"
          docker -D push "ghcr.io/$image"
  update-manifests:
    runs-on: ubuntu-latest
    needs: create-docker-image
    steps:
      - uses: actions/checkout@v2
      - name: Update manifests
        run: |
          sed -i -r -e "s/panther:\w+/panther:$(git rev-parse --short HEAD)/i" manifests/deployment.yaml
      - name: Commit update
        run: |
          git config user.email "actions@github.com" && \
          git config user.name "Github Action" && \
          git add manifests/deployment.yaml && \
          git commit -m "Update target image tag" && \
          git push
